# Site settings
title: ashvin.me
email: nair.ashvin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A gathering place for my projects
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ashvin.me" # the base hostname & protocol for your site
github_username:  anair13

# Build settings
markdown: kramdown